project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: Columbia Center on Poverty and Social Policy
  author:
    - Zhiyan Yang (zy2745)
  repo-url: https://github.com/ClaudiaYang/Columbia-Center-on-Poverty-and-Social-Policy.git
  date: 11/12/2025
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - Week_1.qmd
    - Week_2.qmd
    - Week_3.qmd
    - Week_4.qmd
    - project_conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


